"""Compile content/ into web/game_data.js for the browser runner.

Every piece of player-visible text is pre-analyzed so the runner knows, for
each word, its lemma (for tap-for-help, the notebook, and the "words I
understand" count) without shipping a lemmatizer to the browser.

    python tools/build_game.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from zeit.check import CONTENT, analyze_text, load_config, run  # noqa: E402
from zeit.lexicon import Lexicon  # noqa: E402
from zeit.scenes import load_scenes, validate_links  # noqa: E402

OUT = ROOT / "web" / "game_data.js"


def segments(text: str, lex: Lexicon, day: int, used: dict) -> list:
    """Split text into plain strings and [surface, lemma] pairs."""
    toks = analyze_text(text, lex, day)
    marks = []
    for tk in toks:
        if tk.res.status != "ok":
            continue
        lemma = tk.res.lemma
        used.setdefault(lemma, tk.res)
        marks.append((tk.idx, tk.idx + len(tk.text), lemma))
        if tk.particle_idx >= 0:
            end = tk.particle_idx
            while end < len(text) and text[end].isalpha():
                end += 1
            marks.append((tk.particle_idx, end, lemma))
    marks.sort()
    out, pos = [], 0
    for a, b, lemma in marks:
        if a < pos:
            continue
        if a > pos:
            out.append(text[pos:a])
        out.append([text[a:b], lemma])
        pos = b
    if pos < len(text):
        out.append(text[pos:])
    return out


def word_info(lemma: str, res, lex: Lexicon) -> dict:
    e = lex.entries.get(lemma)
    info = {}
    if e:
        info["k"] = e.kind
        if e.kind == "goethe":
            info["lvl"] = e.level
        if e.hilfe:
            info["h"] = e.hilfe
    if res.how in ("derived", "compound") and res.parts:
        info["teile"] = [p for p in res.parts]
    return info


def main() -> int:
    cfg = load_config()
    lex = Lexicon(cfg["tier_days"], cfg["player"]["assumed_known"])
    scenes = load_scenes(CONTENT)
    errors = validate_links(scenes)
    res = run(scenes, lex, cfg)
    errors += [e for r in res["reports"] for e in r.errors]
    if errors:
        print("Der Checker meldet Fehler. Bitte zuerst `python -m zeit.check` ausführen.")
        for e in errors[:20]:
            print("  ", e)
        return 1

    used: dict = {}
    data = {"order": [], "scenes": {}}
    for sc in scenes:
        nodes = {}
        for name, lines in sc.nodes.items():
            out = []
            for ln in lines:
                item = {"k": ln.kind}
                if ln.text:
                    item["t"] = segments(ln.text, lex, sc.day, used)
                if ln.speaker:
                    item["s"] = ln.speaker
                if ln.target:
                    item["to"] = ln.target
                if ln.cond:
                    item["if"] = ln.cond
                if ln.effects:
                    item["fx"] = ln.effects
                out.append(item)
            nodes[name] = out
        data["order"].append(sc.id)
        data["scenes"][sc.id] = {"tag": sc.day, "titel": sc.meta.get("titel", sc.id),
                                 "ort": sc.meta.get("ort", ""), "nodes": nodes,
                                 "neu": [l for r in res["reports"] if r.scene is sc for l in r.new]}
    data["words"] = {l: word_info(l, r, lex) for l, r in sorted(used.items())}
    data["known_levels"] = sorted(lex.assumed_known)
    OUT.write_text("// generated by tools/build_game.py, do not edit\nwindow.GAME = "
                   + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n",
                   encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(scenes)} Szenen, {len(data['words'])} Wörter")
    return 0


if __name__ == "__main__":
    sys.exit(main())
